name: Build and test
on:
  push:
    branches:
      -main
      -develop
      -'feature/*'
  pull-request:
    types: [opened,synchronize,reopened]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{secrets.GUTHUB_TOKEN}}
          SONAR_LOGIN: ${{ secrets.SONAR_TOKEN}}
        run: mvn clean install -B -DskipTests sonar:sonar -Dsonar.login=$SONAR_LOGIN

